// <auto-generated />
using Artisanaux.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Artisanaux.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221206092704_boutainaMigration")]
    partial class boutainaMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Artisanaux.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 2,
                            CategoryName = "categorie 1",
                            ImageURL = "https://artisana.blob.core.windows.net/artisana/1.jpg",
                            Price = 123.0,
                            ProductName = "Tapis"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "categorie 2",
                            ImageURL = "https://artisana.blob.core.windows.net/artisana/2.jpg",
                            Price = 15.0,
                            ProductName = "Sacs"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "categorie 3",
                            ImageURL = "https://artisana.blob.core.windows.net/artisana/3.jpeg",
                            Price = 123.0,
                            ProductName = "Couvre"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "categorie 4",
                            ImageURL = "https://artisana.blob.core.windows.net/artisana/4.jpg",
                            Price = 123.0,
                            ProductName = "Vers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
